### ISSUE TITLE
numérotation des <item>

### ISSUE THREAD

**Issue by gabays** [e-ditiones/CAT#10]
Numérotation des ```<item>``` non numérotés dans l'original, surtout si seulement quelques-uns sont encodés et qu'un jour on encode tout le catalogue?
Cf. par exemple [CAT_000094](https://github.com/e-ditiones/CAT/blob/master/CAT_000094.xml)

**Comment by lairaines** [comment]
Quel a été le principe de sélection des items encodés ?
Si c'est des pages entières et que tu en as la référence, je défendrais  une identification de forme CAT_000094_n°depage_n°itemdanslapage
Si c'est un choix plus disparate, une possibilité est de numéroter sous la forme
CAT_000094_1_1 et numération continue, comme ça ne force pas à changer les numéros et les références si un jour on complète. Les items nouveaux seraient alors CAT_000094_2_1, etc.

**Comment by gabays** [comment]
Excellente remarque, qui rejoint une préoccupation plus générale quant à ces histoires de numérotation. Pour la [vente Walpole](https://github.com/e-ditiones/CAT/blob/master/CAT_000097.xml), la numérotation recommence pour chaque vacation, j'ai donc fait un truc du genre pour le moment.

```{XML}
<item n="113" xml:id="CAT_000097_Day6e113">
   <num>113.</num>
   <desc>Four letters of the celebrated Madame de Sévigné, extremely
      scarce and curious</desc>
   <add corresp="CAT_000097_w1">
      <num value="000" type="pound">4 14 4</num>
      <note>Vendu à Thorpe</note>
   </add>
</item>
```

On pourrait, si ces préfixes ne sont pas déjà pris, ```CAT_000097_d6e113``` pour 6ème jour, entrée 113, ou ```CAT_000097_p6e113``` pour page 6 entrée 113.

**Comment by lairaines** [comment]
Oui, c'est une très bonne solution car ça ne multiplie pas les tirets inutilement !

**Comment by lairaines** [comment]
J'ai rajouté des précisions sur la numérotation dans la documentation.
