### ISSUE TITLE
<name>

### ISSUE THREAD

**Issue by gabays** [e-ditiones/CAT#13]
On devrait pouvoir ajouter un ```@ref``` sur les ```<name>``` pour faire un lien avec le dossier [PE1](https://github.com/e-ditiones/PE1). Par ex. ```<name ref="#PE1_000001">SÉVIGNÉ (Marie de Rabutin Chantal, marquise de).</name>```. Cf. [CAT_000098](https://github.com/e-ditiones/CAT/blob/master/CAT_000098.xml).

**Comment by lairaines** [comment]
Je viens de mettre le schéma à jour en ce sens et de mon côté ca marche pour le catalogue 98. Si c'est bon de ton côté avec le nouveau schéma tu peux fermer l'issue ?
