### ISSUE TITLE
Trois fois rien

### ISSUE THREAD

**Issue by gabays** [e-ditiones/CAT#4]
@lairaines :
1.  Est-ce que ça ne vaut pas le coup de mettre un ```<xsl:strip-space elements="*"/>``` dans le XSLT pour avoir un doc XML plus lisible?
2. Ne faudrait-il pas ajouter la date de publication du catalogue dans [_listCAT.tsv](https://github.com/e-ditiones/CAT/blob/master/_listCAT.tsv)? Sinon on a une liste illisible de catalogues Charavay.

**Comment by lairaines** [comment]
pour le point 2, j'avais inclus le numéro du catalogue mais il ne s'affiche pas sur Github parce que les titres sont trop longs. Je peux éventuellement intervertir la colonne numéro et la colonne titre pour que ce soit plus visible...
Je peux aussi ajouter une colonne date si besoin (qui aurait l'avantage de concerner tous les types de catalogues).
En intercalant numéro et date avant le titre on devrait avoir quelque chose d'à peu près lisible
