### ISSUE TITLE
<list>

### ISSUE THREAD

**Issue by gabays** [e-ditiones/CAT#5]
Quand je veux mettre un ```<list>``` dans un ```<list>``` (pour faire des sous-entrées), il me demande de mettre un ```<add>``` entre les deux.

**Comment by gabays** [comment]
Je reformule car je ne suis effectivement pas clair. On avait soulevé le problème de lots contenant plusieurs documents différents. Par ex.:

<img width="506" alt="Screen Shot 2019-07-22 at 20 35 00" src="https://user-images.githubusercontent.com/26046460/61656092-3be3e480-acc0-11e9-8d24-5295d1bfce10.png">

Comment encodes-tu cela avec le schéma prévu?

**Comment by lairaines** [comment]
Dans ce cas précis, je mettrai une balise <num>, une balise <desc> pour le premier paragraphe (ce serait artificiel de mettre un <name> et un <trait>) et une balise <note> pour le deuxième paragraphe. 
D'autant plus que ci-dessus, il est difficile d'identifier des documents particuliers / lettres individuelles. 
Ce n'est pas validé par le schéma intermédiaire (à cause des règles schematron) mais c'est valide dans le schéma final. 

Dans le cas des sous-entrées numérotées où les documents sont fortement distinguées et identifiables (par exemple: LAVOISIER ... 1° Mémoire ... 2° Lettre) et qui sont présentes dans les catalogues Laverdet et ceux d'enchères, la mise en forme automatique avec GROBID dictionaries n'était pas très concluante. Il est toujours possible de les encoder en insérant manuellement une <list> et des <items> à l'intérieur de la balise <desc>. Le cas est presque absent de la _Revue des Autographes_, je n'y ai pas été confrontée dans la première série que j'ai encodée. Si ça te parait une solution acceptable, je rajouterai quelques lignes en ce sens dans la documentation.

**Comment by gabays** [comment]
```<list>``` dans ```<list>``` n'est pas possible, mais ```<list>``` dans ```<item>``` oui, comme dans le cas de [CAT_000012.xml](https://github.com/e-ditiones/CAT/blob/master/CAT_000012.xml) dont nous avons parlé fin mai.

Comme je ne mesure pas parfaitement les implications de ce problème sur ce que tu as déjà fait et que mettre ```<list>``` dans ```<desc>``` est sémantiquement viable, je te laisse décider!

**Comment by lairaines** [comment]
Il me semble que la manière la plus simple et la plus cohérente d'encoder doit s'appuyer sur la mise en page. Après tout, c'est cela qui nous permet de différencier ce qui relève de `desc` et ce qui relève de `note`.

Dans le cas du CAT_000012.xml que tu cites, les `desc` et les `note` alternent : dans le lot donné, une liste de sous-lots me parait cohérente, d'autant plus que ça permettrait si besoin d'attribuer aux lettres individuelles un xml:id pour une mise en relation encore plus précise des manuscrits et des catalogues (parce que si je ne me trompe pas, le MS_000004.xml ne contient qu'une des deux lettres du lot ?)

Dans le cas où il n'y a que deux paragraphes relevant de `sense` (par exemple, l'image de la conversation et/ou des lots vendus dans les catalogues de vente à prix marqués), c'est-à-dire quand la `note` est globale (de même que le prix), on créerait dans `desc`une `list` de `item` en laissant le prix à l'extérieur de `list` mais dans `desc`.

Qu'en penses-tu ? (au niveau du schéma, les changements sont très légers mais si la solution te parait bonne, je développerai la documentation et mettrait des images).

**Comment by gabays** [comment]
Validé.
