### ISSUE TITLE
<event>

### ISSUE THREAD

**Issue by gabays** [e-ditiones/CAT#7]
Deux choses:

1. Ne faudrait-il pas utiliser ```<ab>```, ou même ```<desc>```, plutôt que ```<p>```dans les ```<event>```?

2. Il faudrait rajouter un ```@type="identification"``` à ```<event>``` pour les catalogues vendus anonymement mais pour lesquels on a découvert le nom du collectionneur.

**Comment by lairaines** [comment]
Pour le point 1, c'est tout à fait vrai (et je m'attelle à écrire un petit script pour changer ça dans les 100 catalogues sans les ouvrir un par un.

Pour le point 2, je note ça dans les modifications à apporter mais j'ai une question : pourquoi dans ce cas précis, ne pas se servir, dans la section `event` de la balise `persName type= collector`en précisant que l'identification est de la responsabilité de l'éditeur d'un témoin (avec un attribut wit ou un ref, ou même une balise `note` dans `persName`) ? Je peux néanmoins créer le type identification parce que dans l'exemple que j'ai regardé il me semble que c'est un renvoi à un catalogue de documents volés plus qu'une identification de collectionneur ?

**Comment by gabays** [comment]
1. Qu'entends-tu par "éditeur du témoin": l'éditeur scientifique (c'e-à-d nous)?
2. Le _Dictionnaire de pièces autographes volées aux bibliothèques_ de Lalanne, comme _L'Amateur d'autographe_  de Charavay, sont les principales sources pour ces attributions. Dans la mesure où il convient de sourcer l'attribution, je serai partisan de proposer une bibliographie, et donc qu'un ```< event @type="identification">``` convienne bien. D'autant que la découverte du collectionneur est au deux sens du mot un "événement".

**Comment by lairaines** [comment]
Oui, je voulais effectivement dire éditeur du catalogue au sens de nous, les personnes listées dans COL.
Très bien, j'ajoute le type identification

**Comment by lairaines** [comment]
Le type identification a été créé dans les différents schémas et la documentation mise à jour en conséquence.
